Adding JaCoCo Maven plugin for test coverage reports
telicent-oss/rdf-abac pull request #66
Opened 2024-10-29 13:29 UTC by robwtelicent

This PR adds a new Maven module `rdf-abac-coverage-report` which just contains a pom file to create an aggregated coverage report of the Java code in the other Maven modules. This enables you to see all the results from one HTML file.

2024-10-29 14:07 UTC, TelicentPaul requested changes
Long overdue and something we should have across all our repos in a consistent manner.



Do we need the new module?  If it's removed Jacoco still works, admittedly it will generate reports for each individual module.
./rdf-abac-core/target/site/jacoco/index.html
./rdf-abac-fuseki/target/site/jacoco/index.html

but if we add the following: 
`<execution>
            <id>report-aggregate</id>
            <phase>verify</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
</execution>
`          
The aggregated report will be generated in the top level /target/site/jacoco-aggregate/ directory.

2024-10-29 14:47 UTC, robwtelicent commented
@TelicentPaul I'm not sure. I tried your suggestion by removing the extra module and adding the execution to the parent pom. When I run `mvn clean verify` I do get a report in the top level target folder it is empty. I haven't used JaCoCo in a multi-module project before so I followed the guidance here: https://www.baeldung.com/maven-jacoco-multi-module-project

2024-10-30 09:14 UTC, TelicentPaul commented
Fair enough. I'm happy to drop for now.

2024-10-30 09:15 UTC, TelicentPaul approved these changes

2024-10-30 15:53 UTC, TelicentPaul approved these changes

2024-10-30 15:55 UTC, merged